"""empty message

Revision ID: 2c8c53652ff3
Revises: e0b368c0d551
Create Date: 2025-12-17 15:27:37.898376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8c53652ff3'
down_revision = 'e0b368c0d551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_giornaliero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_giornaliero_data'))
        batch_op.create_index(batch_op.f('ix_menu_giornaliero_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_giornaliero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_giornaliero_data'))
        batch_op.create_index(batch_op.f('ix_menu_giornaliero_data'), ['data'], unique=1)

    # ### end Alembic commands ###
