"""User table

Revision ID: e0b368c0d551
Revises: 
Create Date: 2025-12-04 10:06:06.994872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b368c0d551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('matricola', sa.String(length=20), nullable=True),
    sa.Column('is_gestore', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricola')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('menu_giornaliero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('primo', sa.String(length=200), nullable=False),
    sa.Column('secondo', sa.String(length=200), nullable=False),
    sa.Column('contorno', sa.String(length=200), nullable=False),
    sa.Column('frutta', sa.String(length=200), nullable=True),
    sa.Column('dolce', sa.String(length=200), nullable=True),
    sa.Column('prezzo', sa.Float(), nullable=False),
    sa.Column('disponibile', sa.Boolean(), nullable=False),
    sa.Column('gestore_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestore_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_giornaliero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_giornaliero_data'), ['data'], unique=True)
        batch_op.create_index(batch_op.f('ix_menu_giornaliero_gestore_id'), ['gestore_id'], unique=False)

    op.create_table('prenotazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('orario_ritiro', sa.String(length=10), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_giornaliero.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prenotazione', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prenotazione_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prenotazione_utente_id'), ['utente_id'], unique=False)

    op.create_table('transazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('prenotazione_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prenotazione_id'], ['prenotazione.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transazione', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transazione_prenotazione_id'), ['prenotazione_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transazione_utente_id'), ['utente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transazione', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transazione_utente_id'))
        batch_op.drop_index(batch_op.f('ix_transazione_prenotazione_id'))

    op.drop_table('transazione')
    with op.batch_alter_table('prenotazione', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prenotazione_utente_id'))
        batch_op.drop_index(batch_op.f('ix_prenotazione_menu_id'))

    op.drop_table('prenotazione')
    with op.batch_alter_table('menu_giornaliero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_giornaliero_gestore_id'))
        batch_op.drop_index(batch_op.f('ix_menu_giornaliero_data'))

    op.drop_table('menu_giornaliero')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
